### ISSUE TITLE
Bug, player get stuck when hitting corners

### ISSUE THREAD

**Issue by IsBebs** [Luffiez/LowRezJam_1#24]
![bild](https://user-images.githubusercontent.com/33869439/128597749-ecb3a013-344d-44f3-8bdb-adc57f56714e.png)
 happens in the first room. You need only to touch the wall.

**Comment by Luffiez** [comment]
Noticed it as well, maybe we should use a circle collider for the player instead. I think that might resolve the issue

**Comment by Luffiez** [comment]
[Solved by using a CompositeCollider2D](https://gamedev.stackexchange.com/questions/168600/player-gets-stuck-on-edges-between-tilemapcollider2d-tiles)
